# Generated by Django 2.0.5 on 2018-06-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remoteordering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordered_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('Table_No', models.IntegerField()),
                ('Items', models.CharField(max_length=250)),
                ('Time_of_order', models.DateTimeField(verbose_name='Time of order')),
                ('Estimated_Time', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=250)),
            ],
        ),
    ]
