# Generated by Django 2.0.5 on 2018-06-02 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remoteordering', '0002_ordered_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered_items',
            name='item_id',
        ),
    ]
