# Generated by Django 2.0.5 on 2018-06-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remoteordering', '0003_remove_ordered_items_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_No', models.IntegerField()),
                ('Item_id', models.IntegerField()),
                ('Item_name', models.CharField(max_length=250)),
                ('Quantity', models.IntegerField()),
                ('Time_of_order', models.DateTimeField(verbose_name='Time of order')),
                ('Status', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordered_items',
            name='Estimated_Time',
        ),
        migrations.RemoveField(
            model_name='ordered_items',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='ordered_items',
            name='Time_of_order',
        ),
        migrations.AddField(
            model_name='ordered_items',
            name='Bill_Amount',
            field=models.IntegerField(default=0),
        ),
    ]
