# Generated by Django 2.0.5 on 2018-06-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remoteordering', '0004_auto_20180605_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_No', models.IntegerField()),
                ('Items', models.CharField(max_length=250)),
                ('Bill_Amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Ordered_items',
        ),
    ]
