# Generated by Django 2.0.5 on 2018-06-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remoteordering', '0005_auto_20180605_0833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu_items',
            new_name='Menu_item',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
