# Generated by Django 2.0.5 on 2018-06-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remoteordering', '0006_auto_20180605_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='Image_url',
            field=models.CharField(default='images/1.jpg', max_length=1000),
            preserve_default=False,
        ),
    ]
