# Generated by Django 2.0.5 on 2018-06-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remoteordering', '0007_menu_item_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Bill_Amount',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
