# Generated by Django 2.0.5 on 2018-06-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remoteordering', '0010_auto_20180611_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Bill_Amount',
            field=models.IntegerField(),
        ),
    ]
