# Generated by Django 2.0.6 on 2018-06-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remoteordering', '0011_auto_20180611_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Name',
            field=models.CharField(default='sandeep', max_length=250),
            preserve_default=False,
        ),
    ]
