# Generated by Django 2.0.5 on 2018-06-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remoteordering', '0013_auto_20180615_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Name',
            field=models.CharField(default='paid', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Status',
            field=models.CharField(default='paid', max_length=250),
            preserve_default=False,
        ),
    ]
